name: Update Angelman Trials JSON

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run update script
        run: |
          python update_trials.py

      - name: Commit and push if changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add angelman-clinical-trials.json
          git diff --cached --quiet || git commit -m "🔄 Auto-update Angelman trial data"
          git push
